---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}-{{.Iteration}}-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: {{.name}}-{{.Iteration}}
  template:
    metadata:
      labels:
        app: {{.name}}-{{.Iteration}}
    spec:
      nodeSelector:
        {{.nodeSelectorKey}}: {{.nodeSelectorValue}}
      containers:
      - args:
        - sleep
        - infinity
        image: quay.io/openshift-scale/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        name: {{.name}}
