kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: nginx-{{.Iteration}}
    spec:
      nodeSelector:
        {{.nodeSelectorKey}}: {{.nodeSelectorValue}}
      containers:
      - name: nginx
        image: quay.io/openshift-scale/nginx
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: nginx-{{.Iteration}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
